// @ts-nocheck
/**
 * DefaultRPGTileset — generates an 8-bit RPG tileset with pixel art patterns.
 *
 * Creates tile patterns for grass, water, trees, buildings, paths, etc.
 * Each tile is 8×8 pixels with palette indices. These get rendered by
 * TileRenderer into PixiJS textures for use in DemoWorld/WorldScene.
 */
import { Tileset } from "../../shared/Tileset";
import { Palette, BobColor } from "../../shared/Palette";

export class DefaultRPGTileset {
	/** Tile IDs for the default RPG tileset */
	static readonly TILES = {
		EMPTY: 0,
		GRASS_1: 1,
		GRASS_2: 2,
		GRASS_3: 3,
		PATH: 4,
		WATER_1: 5,
		WATER_2: 6,
		TREE_TRUNK: 7,
		TREE_LEAVES: 8,
		BUILDING_WALL: 9,
		BUILDING_ROOF: 10,
		DOOR: 11,
		FLOOR: 12,
		SAND: 13,
		FLOWER_RED: 14,
		FLOWER_BLUE: 15,
		BRIDGE: 16,
		FENCE: 17,
		CHEST: 18,
		STAIR_DOWN: 19,
		STAIR_UP: 20,
		WINDOW: 21,
		SIGN: 22,
		STONE: 23,
	} as const;

	/** Palette color indices */
	private static readonly P = {
		TRANSPARENT: 0,
		BLACK: 1,
		WHITE: 2,
		DARK_GREEN: 3,
		GREEN: 4,
		LIGHT_GREEN: 5,
		DARK_BLUE: 6,
		BLUE: 7,
		LIGHT_BLUE: 8,
		BROWN: 9,
		DARK_BROWN: 10,
		TAN: 11,
		GRAY: 12,
		DARK_GRAY: 13,
		RED: 14,
		YELLOW: 15,
		SAND_COLOR: 16,
		ORANGE: 17,
		ROOF_RED: 18,
		PINK: 19,
	};

	/**
	 * Create the default RPG palette with 20 colors.
	 */
	static createPalette(): Palette {
		const p = new Palette(32);
		p.setColor(0, new BobColor(0, 0, 0, 0));       // transparent
		p.setColor(1, new BobColor(0, 0, 0, 255));      // black
		p.setColor(2, new BobColor(255, 255, 255, 255)); // white
		p.setColor(3, new BobColor(20, 80, 20, 255));    // dark green
		p.setColor(4, new BobColor(45, 140, 45, 255));   // green
		p.setColor(5, new BobColor(90, 200, 90, 255));   // light green
		p.setColor(6, new BobColor(20, 40, 120, 255));   // dark blue
		p.setColor(7, new BobColor(40, 80, 180, 255));   // blue
		p.setColor(8, new BobColor(100, 160, 240, 255)); // light blue
		p.setColor(9, new BobColor(120, 80, 40, 255));   // brown
		p.setColor(10, new BobColor(80, 50, 25, 255));   // dark brown
		p.setColor(11, new BobColor(180, 150, 100, 255)); // tan
		p.setColor(12, new BobColor(140, 140, 140, 255)); // gray
		p.setColor(13, new BobColor(80, 80, 80, 255));    // dark gray
		p.setColor(14, new BobColor(220, 40, 40, 255));   // red
		p.setColor(15, new BobColor(240, 220, 60, 255));  // yellow
		p.setColor(16, new BobColor(210, 190, 140, 255)); // sand
		p.setColor(17, new BobColor(240, 160, 40, 255));  // orange
		p.setColor(18, new BobColor(180, 60, 50, 255));   // roof red
		p.setColor(19, new BobColor(240, 120, 160, 255)); // pink
		return p;
	}

	/**
	 * Generate the full default RPG tileset.
	 * Each tile is 8×8 pixels using palette color indices.
	 */
	static generate(): Tileset {
		const ts = new Tileset(30);
		const P = DefaultRPGTileset.P;

		// Helper to fill a tile with a single color
		const fill = (tile: number, color: number) => {
			for (let y = 0; y < 8; y++)
				for (let x = 0; x < 8; x++)
					ts.setPixel(tile, x, y, color);
		};

		// Helper to set a pattern
		const pattern = (tile: number, rows: number[][]) => {
			for (let y = 0; y < rows.length && y < 8; y++)
				for (let x = 0; x < rows[y].length && x < 8; x++)
					ts.setPixel(tile, x, y, rows[y][x]);
		};

		// Tile 0: EMPTY (transparent)
		fill(0, P.TRANSPARENT);

		// Tile 1: GRASS_1 — base grass with dark green spots
		pattern(1, [
			[P.DARK_GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN, P.DARK_GREEN, P.GREEN],
			[P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN, P.DARK_GREEN, P.GREEN, P.GREEN],
			[P.GREEN, P.DARK_GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN],
			[P.LIGHT_GREEN, P.GREEN, P.GREEN, P.DARK_GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN],
			[P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN, P.DARK_GREEN, P.GREEN, P.GREEN],
			[P.DARK_GREEN, P.GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN, P.DARK_GREEN],
			[P.GREEN, P.LIGHT_GREEN, P.GREEN, P.DARK_GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN],
			[P.GREEN, P.GREEN, P.DARK_GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN],
		]);

		// Tile 2: GRASS_2 — variation
		pattern(2, [
			[P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.DARK_GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN],
			[P.GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN, P.GREEN, P.GREEN, P.DARK_GREEN, P.GREEN],
			[P.DARK_GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN, P.GREEN, P.GREEN],
			[P.GREEN, P.GREEN, P.GREEN, P.GREEN, P.DARK_GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN],
			[P.LIGHT_GREEN, P.GREEN, P.DARK_GREEN, P.GREEN, P.GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN],
			[P.GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN, P.DARK_GREEN, P.GREEN],
			[P.GREEN, P.DARK_GREEN, P.GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN],
			[P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN, P.GREEN, P.GREEN, P.DARK_GREEN],
		]);

		// Tile 3: GRASS_3 — another variation
		fill(3, P.GREEN);
		ts.setPixel(3, 1, 3, P.LIGHT_GREEN);
		ts.setPixel(3, 5, 1, P.LIGHT_GREEN);
		ts.setPixel(3, 2, 6, P.DARK_GREEN);
		ts.setPixel(3, 7, 4, P.DARK_GREEN);

		// Tile 4: PATH — tan/dirt
		pattern(4, [
			[P.TAN, P.BROWN, P.TAN, P.TAN, P.BROWN, P.TAN, P.TAN, P.BROWN],
			[P.TAN, P.TAN, P.BROWN, P.TAN, P.TAN, P.TAN, P.BROWN, P.TAN],
			[P.BROWN, P.TAN, P.TAN, P.TAN, P.TAN, P.BROWN, P.TAN, P.TAN],
			[P.TAN, P.TAN, P.TAN, P.BROWN, P.TAN, P.TAN, P.TAN, P.TAN],
			[P.TAN, P.TAN, P.BROWN, P.TAN, P.TAN, P.TAN, P.BROWN, P.TAN],
			[P.TAN, P.TAN, P.TAN, P.TAN, P.BROWN, P.TAN, P.TAN, P.TAN],
			[P.TAN, P.BROWN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.BROWN],
			[P.TAN, P.TAN, P.TAN, P.BROWN, P.TAN, P.TAN, P.TAN, P.TAN],
		]);

		// Tile 5: WATER_1 — dark water
		pattern(5, [
			[P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE],
			[P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE],
			[P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE],
			[P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE],
			[P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE],
			[P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE],
			[P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE],
			[P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE],
		]);

		// Tile 6: WATER_2 — lighter wave
		pattern(6, [
			[P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.LIGHT_BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE],
			[P.DARK_BLUE, P.BLUE, P.LIGHT_BLUE, P.BLUE, P.DARK_BLUE, P.BLUE, P.LIGHT_BLUE, P.DARK_BLUE],
			[P.BLUE, P.LIGHT_BLUE, P.BLUE, P.DARK_BLUE, P.BLUE, P.LIGHT_BLUE, P.BLUE, P.DARK_BLUE],
			[P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.LIGHT_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE],
			[P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.LIGHT_BLUE, P.DARK_BLUE, P.DARK_BLUE, P.BLUE, P.DARK_BLUE],
			[P.DARK_BLUE, P.BLUE, P.LIGHT_BLUE, P.BLUE, P.DARK_BLUE, P.BLUE, P.LIGHT_BLUE, P.DARK_BLUE],
			[P.BLUE, P.LIGHT_BLUE, P.BLUE, P.DARK_BLUE, P.BLUE, P.LIGHT_BLUE, P.BLUE, P.DARK_BLUE],
			[P.DARK_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE, P.LIGHT_BLUE, P.BLUE, P.DARK_BLUE, P.DARK_BLUE],
		]);

		// Tile 7: TREE_TRUNK
		fill(7, P.TRANSPARENT);
		pattern(7, [
			[P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.DARK_BROWN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.BROWN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.BROWN, P.DARK_BROWN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.BROWN, P.DARK_BROWN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.BROWN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
		]);

		// Tile 8: TREE_LEAVES
		pattern(8, [
			[P.TRANSPARENT, P.TRANSPARENT, P.DARK_GREEN, P.DARK_GREEN, P.DARK_GREEN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.DARK_GREEN, P.GREEN, P.GREEN, P.GREEN, P.DARK_GREEN, P.TRANSPARENT, P.TRANSPARENT],
			[P.DARK_GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.DARK_GREEN, P.TRANSPARENT],
			[P.DARK_GREEN, P.GREEN, P.GREEN, P.GREEN, P.GREEN, P.GREEN, P.GREEN, P.DARK_GREEN],
			[P.DARK_GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.GREEN, P.LIGHT_GREEN, P.GREEN, P.DARK_GREEN],
			[P.TRANSPARENT, P.DARK_GREEN, P.GREEN, P.GREEN, P.GREEN, P.GREEN, P.DARK_GREEN, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.DARK_GREEN, P.GREEN, P.DARK_GREEN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.DARK_GREEN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
		]);

		// Tile 9: BUILDING_WALL
		pattern(9, [
			[P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN],
			[P.TAN, P.BROWN, P.TAN, P.TAN, P.TAN, P.BROWN, P.TAN, P.TAN],
			[P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN],
			[P.BROWN, P.TAN, P.TAN, P.BROWN, P.BROWN, P.TAN, P.TAN, P.BROWN],
			[P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN],
			[P.TAN, P.BROWN, P.TAN, P.TAN, P.TAN, P.BROWN, P.TAN, P.TAN],
			[P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN],
			[P.BROWN, P.TAN, P.TAN, P.BROWN, P.BROWN, P.TAN, P.TAN, P.BROWN],
		]);

		// Tile 10: BUILDING_ROOF
		pattern(10, [
			[P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY],
			[P.DARK_GRAY, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.DARK_GRAY],
			[P.DARK_GRAY, P.ROOF_RED, P.ORANGE, P.ROOF_RED, P.ROOF_RED, P.ORANGE, P.ROOF_RED, P.DARK_GRAY],
			[P.DARK_GRAY, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.DARK_GRAY],
			[P.DARK_GRAY, P.ROOF_RED, P.ROOF_RED, P.ORANGE, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.DARK_GRAY],
			[P.DARK_GRAY, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.ROOF_RED, P.DARK_GRAY],
			[P.DARK_GRAY, P.ROOF_RED, P.ORANGE, P.ROOF_RED, P.ROOF_RED, P.ORANGE, P.ROOF_RED, P.DARK_GRAY],
			[P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY],
		]);

		// Tile 11: DOOR
		pattern(11, [
			[P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.YELLOW, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN],
		]);

		// Tile 12: FLOOR
		pattern(12, [
			[P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN],
			[P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN],
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN],
			[P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN],
			[P.BROWN, P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN, P.BROWN, P.BROWN],
			[P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN],
			[P.BROWN, P.BROWN, P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN, P.BROWN],
			[P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN],
		]);

		// Tile 13: SAND
		pattern(13, [
			[P.SAND_COLOR, P.SAND_COLOR, P.TAN, P.SAND_COLOR, P.SAND_COLOR, P.SAND_COLOR, P.TAN, P.SAND_COLOR],
			[P.SAND_COLOR, P.TAN, P.SAND_COLOR, P.SAND_COLOR, P.SAND_COLOR, P.TAN, P.SAND_COLOR, P.SAND_COLOR],
			[P.TAN, P.SAND_COLOR, P.SAND_COLOR, P.TAN, P.SAND_COLOR, P.SAND_COLOR, P.SAND_COLOR, P.SAND_COLOR],
			[P.SAND_COLOR, P.SAND_COLOR, P.SAND_COLOR, P.SAND_COLOR, P.TAN, P.SAND_COLOR, P.SAND_COLOR, P.TAN],
			[P.SAND_COLOR, P.SAND_COLOR, P.TAN, P.SAND_COLOR, P.SAND_COLOR, P.SAND_COLOR, P.TAN, P.SAND_COLOR],
			[P.SAND_COLOR, P.TAN, P.SAND_COLOR, P.SAND_COLOR, P.SAND_COLOR, P.TAN, P.SAND_COLOR, P.SAND_COLOR],
			[P.TAN, P.SAND_COLOR, P.SAND_COLOR, P.TAN, P.SAND_COLOR, P.SAND_COLOR, P.SAND_COLOR, P.SAND_COLOR],
			[P.SAND_COLOR, P.SAND_COLOR, P.SAND_COLOR, P.SAND_COLOR, P.TAN, P.SAND_COLOR, P.SAND_COLOR, P.TAN],
		]);

		// Tile 14: FLOWER_RED
		fill(14, P.TRANSPARENT);
		ts.setPixel(14, 3, 2, P.GREEN);
		ts.setPixel(14, 3, 3, P.GREEN);
		ts.setPixel(14, 3, 4, P.GREEN);
		ts.setPixel(14, 3, 5, P.DARK_GREEN);
		ts.setPixel(14, 2, 2, P.RED);
		ts.setPixel(14, 3, 1, P.RED);
		ts.setPixel(14, 4, 2, P.RED);
		ts.setPixel(14, 3, 3, P.YELLOW);

		// Tile 15: FLOWER_BLUE
		fill(15, P.TRANSPARENT);
		ts.setPixel(15, 5, 4, P.GREEN);
		ts.setPixel(15, 5, 5, P.GREEN);
		ts.setPixel(15, 5, 6, P.GREEN);
		ts.setPixel(15, 5, 7, P.DARK_GREEN);
		ts.setPixel(15, 4, 4, P.LIGHT_BLUE);
		ts.setPixel(15, 5, 3, P.LIGHT_BLUE);
		ts.setPixel(15, 6, 4, P.LIGHT_BLUE);
		ts.setPixel(15, 5, 4, P.YELLOW);

		// Tile 16: BRIDGE
		pattern(16, [
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.DARK_BROWN, P.BROWN, P.BROWN, P.DARK_BROWN, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.DARK_BROWN, P.BROWN, P.BROWN, P.DARK_BROWN, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN],
			[P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN],
		]);

		// Tile 17: FENCE
		fill(17, P.TRANSPARENT);
		for (let y = 0; y < 8; y++) {
			ts.setPixel(17, 1, y, P.BROWN);
			ts.setPixel(17, 6, y, P.BROWN);
		}
		ts.setPixel(17, 1, 2, P.DARK_BROWN);
		ts.setPixel(17, 6, 2, P.DARK_BROWN);
		ts.setPixel(17, 1, 5, P.DARK_BROWN);
		ts.setPixel(17, 6, 5, P.DARK_BROWN);
		for (let x = 1; x < 7; x++) {
			ts.setPixel(17, x, 2, P.BROWN);
			ts.setPixel(17, x, 5, P.BROWN);
		}

		// Tile 18: CHEST
		pattern(18, [
			[P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.DARK_BROWN, P.YELLOW, P.BROWN, P.BROWN, P.YELLOW, P.DARK_BROWN, P.TRANSPARENT],
			[P.TRANSPARENT, P.DARK_BROWN, P.BROWN, P.YELLOW, P.BROWN, P.BROWN, P.DARK_BROWN, P.TRANSPARENT],
			[P.TRANSPARENT, P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN, P.TRANSPARENT],
			[P.TRANSPARENT, P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
		]);

		// Tile 19: STAIR_DOWN
		pattern(19, [
			[P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY],
			[P.DARK_GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.DARK_GRAY],
			[P.DARK_GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.DARK_GRAY],
			[P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY],
			[P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY],
			[P.BLACK, P.BLACK, P.BLACK, P.BLACK, P.BLACK, P.BLACK, P.BLACK, P.BLACK],
			[P.BLACK, P.BLACK, P.BLACK, P.BLACK, P.BLACK, P.BLACK, P.BLACK, P.BLACK],
			[P.BLACK, P.BLACK, P.BLACK, P.BLACK, P.BLACK, P.BLACK, P.BLACK, P.BLACK],
		]);

		// Tile 20: STAIR_UP
		pattern(20, [
			[P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY],
			[P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY],
			[P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY],
			[P.DARK_GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.DARK_GRAY],
			[P.DARK_GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.DARK_GRAY],
			[P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY],
			[P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY, P.GRAY],
			[P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY, P.DARK_GRAY],
		]);

		// Tile 21: WINDOW
		pattern(21, [
			[P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN],
			[P.TAN, P.DARK_BROWN, P.LIGHT_BLUE, P.LIGHT_BLUE, P.LIGHT_BLUE, P.LIGHT_BLUE, P.DARK_BROWN, P.TAN],
			[P.TAN, P.DARK_BROWN, P.LIGHT_BLUE, P.BLUE, P.LIGHT_BLUE, P.BLUE, P.DARK_BROWN, P.TAN],
			[P.TAN, P.DARK_BROWN, P.LIGHT_BLUE, P.LIGHT_BLUE, P.LIGHT_BLUE, P.LIGHT_BLUE, P.DARK_BROWN, P.TAN],
			[P.TAN, P.DARK_BROWN, P.LIGHT_BLUE, P.BLUE, P.LIGHT_BLUE, P.BLUE, P.DARK_BROWN, P.TAN],
			[P.TAN, P.DARK_BROWN, P.LIGHT_BLUE, P.LIGHT_BLUE, P.LIGHT_BLUE, P.LIGHT_BLUE, P.DARK_BROWN, P.TAN],
			[P.TAN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.TAN],
			[P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN, P.TAN],
		]);

		// Tile 22: SIGN
		fill(22, P.TRANSPARENT);
		pattern(22, [
			[P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN, P.TRANSPARENT],
			[P.TRANSPARENT, P.DARK_BROWN, P.BROWN, P.DARK_BROWN, P.BROWN, P.BROWN, P.DARK_BROWN, P.TRANSPARENT],
			[P.TRANSPARENT, P.DARK_BROWN, P.BROWN, P.BROWN, P.BROWN, P.BROWN, P.DARK_BROWN, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.DARK_BROWN, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
			[P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.DARK_BROWN, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT, P.TRANSPARENT],
		]);

		// Tile 23: STONE
		pattern(23, [
			[P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY],
			[P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY],
			[P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY],
			[P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY],
			[P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY],
			[P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY],
			[P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY],
			[P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY, P.DARK_GRAY, P.GRAY, P.GRAY],
		]);

		return ts;
	}
}
